### ISSUE TITLE
Support for TYPO3 Flow 2.3.*

### ISSUE THREAD

**Issue by desaisagar** [dfeyer/TYPO3.Soap#2]
Hello Dominique,

We have installed TYPO3.SOAP package version  "dev-task-42940" having TYPO3.Flow version "2.3.X-dev" and we are getting output as BAD REQUEST 
we also checked with TYPO3.Flow version "2.1._" and its working fine and getting correct output, the latest Flow version is not compatible with the TYPO3.SOAP package. It would be better if you make it compatible with 2.3._.

Thanks!!!
Sagar Desai
https://www.lelesys.com

**Comment by dfeyer** [comment]
If you can sponsor or help on this feature, it will be great. 
I need to push some patch upstream and use HTTP components for Flow 2.3. Count around 2 days of work.

**Comment by desaisagar** [comment]
Hello Dominique,

We are happy to help you on this feature, Can you please let us know which part of this feature is remaining? As it is working for us with your latest patch and we are able to get the correct output.

Thanks!!!
Sagar Desai
https://www.lelesys.com

**Comment by dfeyer** [comment]
The plan is to replace the custom request handler, with the new feature of Flow 2.3, named HTTP components. The code will be simpler, but I need to figure out how to refactor the package

**Comment by dfeyer** [comment]
My current experiment (not working) are here:
https://github.com/dfeyer/TYPO3.Soap/tree/Feature/HttpComponent

And the documentation about the HTTP Component in Flow:
http://docs.typo3.org/flow/TYPO3FlowDocumentation/TheDefinitiveGuide/PartIII/Http.html#component-chain

**Comment by dfeyer** [comment]
Can you test this branch:
https://github.com/dfeyer/TYPO3.Soap/tree/Feature/HttpComponent

:+1: This fix Flow 2.3 compatibility (and now Flow 2.3 is minimum requirement)

If you can confirm that this branch work for your, I can close this issue, and try to found time to push everything upstream.

**Comment by desaisagar** [comment]
Hello Dominique,

We have tested the branch https://github.com/dfeyer/TYPO3.Soap/tree/Feature/HttpComponent and it is working fine for us.

Thanks!!!
Sagar Desai
https://www.lelesys.com

**Comment by dfeyer** [comment]
OK I will merge it later this week, and try to prepare some patch for the upstream package, I wait too long before pushing all those stuff upstream

**Comment by arianesardinas** [comment]
Hello Dominique,

We have tested with TYPO3.Flow version "2.1." we are getting output as BAD REQUEST 

<div style="width: 100%; background-color: #515151; color: white; padding: 2px; margin: 0 0 6px 0;">Uncaught Exception in Flow</div>

```
            <div style="width: 100%; padding: 2px; margin: 0 0 6px 0;">
                <h2 class="ExceptionSubject">#1320164802: Request service path "test.soap/test" is not a valid service endpoint path</h2><p><a href="http://typo3.org/go/exception/1320164802">More information</a></p>
            <span class="ExceptionProperty">TYPO3\Soap\InvalidSoapRequestException</span> thrown in file<br />
            <span class="ExceptionProperty">/html/typo3.flow/Data/Temporary/Development/Cache/Code/Flow_Object_Classes/TYPO3_Soap_RequestBuilder.php</span> in line
            <span class="ExceptionProperty">102</span>.<br /><span class="ExceptionProperty">Reference code: 2015040719062269e489</span><br /><br /><a href="http://forge.typo3.org/projects/package-typo3-flow/issues/new?issue[subject]=TYPO3%5CSoap%5CInvalidSoapRequestException+thrown+in+file+TYPO3_Soap_RequestBuilder.php&issue[description]=Request+service+path+%22test.soap%2Ftest%22+is+not+a+valid+service+endpoint+path%0A4+TYPO3%5CSoap%5CRequestBuilder_Original%3A%3AservicePathForRequestUri%28TYPO3%5CFlow%5CHttp%5CUri%29%0A%0A3+TYPO3%5CSoap%5CRequestBuilder_Original%3A%3Abuild%28TYPO3%5CFlow%5CHttp%5CRequest%29%0A%0A2+TYPO3%5CSoap%5CRequestHandler%3A%3AhandleRequest%28%29%0A%0A1+TYPO3%5CFlow%5CCore%5CBootstrap%3A%3Arun%28%29%0A%0A%0APlease+include+more+helpful+information%21&issue[category_id]=554&issue[priority_id]=7">Go to the FORGE issue tracker and report the issue</a> - <strong>if you think it is a bug!</strong><br />
                <br />
                <pre style="color:#69A550; background-color: #414141; padding: 4px 2px 4px 2px;"><span style="color:white;">4</span> TYPO3\Soap\RequestBuilder_Original<span style="color:white;">::</span>servicePathForRequestUri<span style="color:white;">(<span style="color:#FF8700;"><em>TYPO3\Flow\Http\Uri</em></span>)</span></pre><br /><span style="font-size:10px;">/html/typo3.flow/Data/Temporary/Development/Cache/Code/Flow_Object_Classes/TYPO3_Soap_RequestBuilder.php:</span><br /><pre>00076:   $baseUri = $httpRequest->getBaseUri();
```

00077: 
</pre><pre style="background-color: #F1F1F1; color: black;">00078:   $servicePath = $this->servicePathForRequestUri($requestUri);
</pre><pre>00079:   $serviceObjectName = $this->serviceObjectNameForServicePath($servicePath);
00080: 
</pre><br /><pre style="color:#69A550; background-color: #414141; padding: 4px 2px 4px 2px;"><span style="color:white;">3</span> TYPO3\Soap\RequestBuilder_Original<span style="color:white;">::</span>build<span style="color:white;">(<span style="color:#FF8700;"><em>TYPO3\Flow\Http\Request</em></span>)</span></pre><br /><span style="font-size:10px;">Packages/Framework/TYPO3.Soap/Classes/TYPO3/Soap/RequestHandler.php:</span><br /><pre>00103: 
00104:   $this->objectManager = $this->bootstrap->getObjectManager();
</pre><pre style="background-color: #F1F1F1; color: black;">00105:   $request = $this->objectManager->get('TYPO3\Soap\RequestBuilder')->build($this->httpRequest);
</pre><pre>00106:   if ($request === FALSE) {
00107:    header('HTTP/1.1 404 Not Found');
</pre><br /><pre style="color:#69A550; background-color: #414141; padding: 4px 2px 4px 2px;"><span style="color:white;">2</span> TYPO3\Soap\RequestHandler<span style="color:white;">::</span>handleRequest<span style="color:white;">()</span></pre><br /><span style="font-size:10px;">Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Core/Bootstrap.php:</span><br /><pre>00111: 
00112:   $this->activeRequestHandler = $this->resolveRequestHandler();
</pre><pre style="background-color: #F1F1F1; color: black;">00113:   $this->activeRequestHandler->handleRequest();
</pre><pre>00114:  }
00115: 
</pre><br /><pre style="color:#69A550; background-color: #414141; padding: 4px 2px 4px 2px;"><span style="color:white;">1</span> TYPO3\Flow\Core\Bootstrap<span style="color:white;">::</span>run<span style="color:white;">()</span></pre><br /><span style="font-size:10px;">/html/typo3.flow/Web/index.php:</span><br /><pre>00025: $context = getenv('FLOW_CONTEXT') ?: (getenv('REDIRECT_FLOW_CONTEXT') ?: 'Development');
00026: $bootstrap = new \TYPO3\Flow\Core\Bootstrap($context);
</pre><pre style="background-color: #F1F1F1; color: black;">00027: $bootstrap->run();
</pre><pre></pre><br />
                </div>
            </div>

http://flow3.p186289.webspaceconfig.de/service/soap/test.soap/test.wsdl

can you give me a tip, what am I doing wrong?
